apiVersion: v1
kind: ServiceAccount
metadata:
  name: app
  namespace: default
---
apiVersion: v1
kind: Service
metadata:
  name: app
  namespace: default
spec:
  selector:
    app: app
  ports:
  - protocol: TCP
    port: 80
    targetPort: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      serviceAccountName: app
      containers:
      - name: app
        image: ghcr.io/matheuscscp/gds-hackathon/app:v0.1.0
        ports:
        - containerPort: 8080
          name: http
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
        - name: AWS_REGION
          value: us-west-2
        - name: AWS_ROLE_ARN
          value: arn:aws:iam::211125720409:role/AppRole
        - name: AWS_ROLE_SESSION_NAME
          value: gds-hackathon-app
        - name: AWS_WEB_IDENTITY_TOKEN_FILE
          value: /var/run/secrets/serviceaccount/aws-token
        volumeMounts:
        - name: aws-token
          mountPath: /var/run/secrets/serviceaccount
          readOnly: true
      volumes:
      - name: aws-token
        projected:
          sources:
          - serviceAccountToken:
              audience: sts.amazonaws.com
              expirationSeconds: 3600
              path: aws-token
