name: Push Kubernetes

on:
  push:
    branches: [main]
    paths:
    - kubernetes/**
    - .github/workflows/push-kubernetes.yml

jobs:
  push:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout repository
      uses: actions/checkout@v2
