name: Release Go App

on:
  push:
    tags: [app/v*]

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write # for signing the image
      packages: write # for publishing the Docker image

    steps:

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to GHCR
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build Docker image
      id: build
      working-directory: ./app
      run: |
        # remove the app/ prefix from the tag with bash
        tag=$(echo $tag | sed 's/^app\///')
        tag="$repo:$tag"
        docker build -t $tag .
        docker push $tag | grep digest: | awk '{print $3}' > digest.txt
        echo digest=$(cat digest.txt) >> $GITHUB_OUTPUT
      env:
        repo: ghcr.io/${{ github.repository }}/app
        tag: ${{ github.ref_name }}

    - name: Setup cosign
      uses: sigstore/cosign-installer@v3

    - name: Sign image
      run: cosign sign --yes $digest_url
      env:
        digest_url: ghcr.io/${{ github.repository }}/app@${{ steps.build.outputs.digest }}
